更新上传 APK 脚本

diff --git a/.github/workflows/publish_apk.yml b/.github/workflows/publish_apk.yml
--- a/.github/workflows/publish_apk.yml
+++ b/.github/workflows/publish_apk.yml
@@ -31,4 +31,12 @@ jobs:
       - name: Build APK
         run: cd example && flutter build apk --target-platform android-arm
       - name: Upload to Pgyer
-        run: curl -F 'file=@example/build/app/outputs/apk/release/app-release.apk' -F '_api_key=${{ secrets.PGYER_API_KEY }}' https://www.pgyer.com/apiv2/app/upload
+        run: |
+          result=$(curl -F 'file=@example/build/app/outputs/apk/release/app-release.apk' -F '_api_key=${{ secrets.PGYER_API_KEY }}' https://www.pgyer.com/apiv2/app/upload)
+          if [[ $result != *"{\"code\":0"* ]]; then
+            echo 'result:'$result
+            echo "Upload Pgyer Failed !!!"
+            exit 1
+          fi
+          echo "Upload Pgyer Success"
+          
